<a href="https://colab.research.google.com/github/aksevenli/Pytorch-Reinforcement-Learning/blob/master/PyTorchEssentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

Randomly initialized Matrix

In [16]:
x = torch.rand(3, 4)
print(x)

tensor([[0.1460, 0.5540, 0.1858, 0.6725],
        [0.7075, 0.4117, 0.2409, 0.4165],
        [0.5532, 0.4863, 0.0572, 0.4759]])


Specify data type

In [3]:
x = torch.rand(3, 4, dtype=torch.double)
print(x)

tensor([[0.1211, 0.4514, 0.8394, 0.4944],
        [0.3947, 0.1829, 0.6425, 0.8830],
        [0.2951, 0.2255, 0.1184, 0.0484]], dtype=torch.float64)


Create a matrix full of zeros and a matrix full of ones

In [5]:
x = torch.zeros(3, 4)
print(x)
x = torch.ones(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Get the size of a tensor

In [6]:
print(x.size())

torch.Size([3, 4])


Reshape a tensor

In [7]:
x_reshaped = x.view(2, 6)
print(x_reshaped)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


Create a tensor directly from data, including a single value, a list, and anested list

In [9]:
x1 = torch.tensor(3)
print(x1)
x2 = torch.tensor([14.2, 3, 4])
print(x2)
x3 = torch.tensor([[3, 4, 6], [2, 1.0, 5]])
print(x3)

tensor(3)
tensor([14.2000,  3.0000,  4.0000])
tensor([[3., 4., 6.],
        [2., 1., 5.]])


Access the elements in a tensor of more than one element use indexing

In [10]:
print(x2[1])
print(x3[1, 0])
print(x3[:, 1])
print(x3[:, 1:])

tensor(3.)
tensor(2.)
tensor([4., 1.])
tensor([[4., 6.],
        [1., 5.]])


Convert a NumPy array to a tensor 

In [11]:
import numpy as np
x_np = np.ones(3)
x_torch = torch.from_numpy(x_np)
print(x_torch)

tensor([1., 1., 1.], dtype=torch.float64)


Operations in PyTorch

In [14]:
x4 = torch.tensor([[1, 0, 0], [0, 1.0, 0]])
print(x3 + x4)
# Use add()
print(torch.add(x3, x4))

tensor([[4., 4., 6.],
        [2., 2., 5.]])
tensor([[4., 4., 6.],
        [2., 2., 5.]])


In-place Operations, which mutate the tensor object

In [15]:
x3.add_(x4)

tensor([[4., 4., 6.],
        [2., 2., 5.]])